### ISSUE TITLE
Properties Panel Header Displays Element Template Icon Found in Template Instead of XML

### ISSUE THREAD

**Issue by zxuanhong** [bpmn-io/bpmn-js-properties-panel#1011]
### Is your feature request related to a problem? Please describe.

1. The properties at the top of the icon with ElementTemplateIconRenderer get icon logically consistent. Get it directly from the element or read it from the built-in icon.
2. If the logic is consistent, you can customize the icon of an element
3. Key code ElementTemplateIconRenderer access icon
<img width="843" alt="image" src="https://github.com/bpmn-io/bpmn-js-properties-panel/assets/62740686/78ba2a38-44cf-48ab-894a-65baafaffce4">
4. And now once the template is lost, it will also cause the element icon to render properly, but the properties header icon will not render properly.For example
<img width="1135" alt="image" src="https://github.com/bpmn-io/bpmn-js-properties-panel/assets/62740686/8add2097-687d-4448-984d-7a762454e55c">

**Comment by nikku** [comment]
@zxuanhong We read it from the rendered XML because we want the icon to be present also in the case of missing element template.

Do I understand you correctly that your feature request is to use the same mechanism to read the icon in the properties panel? There we currently read the icon from the connected element template.

**Comment by zxuanhong** [comment]
@nikku yes. this pr will solve this problem #1012
