### ISSUE TITLE
I can edit the name of an element

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#124]
To be consistent we should allow users to change the name of _all_ elements via the properties panel.

Already works for Processes:

![image](https://cloud.githubusercontent.com/assets/58601/12087939/636e24a2-b2d7-11e5-8b28-acfe74610c3f.png)

**Comment by meyerdan** [comment]
The reason the name property was not add was that it is possible to set the name on the diagram itself.
For processes this is not possible which is why an exception was made.
We started with not providing property entries for things that can be modeled using the diagram.

But that does not mean it has to stay this way...

**Comment by nikku** [comment]
Yea. It just seems as if our way of editing the names (double click on the canvas) is non-intuitive for some properties panel users. So adding name editing there may be an additional help.

Not to urgent right now. Just wanted to have an issue where we collect feedback regarding this :wink:.

**Comment by berndruecker** [comment]
+1

**Comment by soulmate2015** [comment]
I want to use the element `name` in every Events. Not only for Processes. So I suggest to add custom property for Events, this is optional.
