### ISSUE TITLE
Custom css classes for property elements

### ISSUE THREAD

**Issue by albertodlh** [bpmn-io/bpmn-js-properties-panel#200]
Hello. Currently, there is no way for adding custom css classes to the property elements. We have been working on a fork that allows this by sending a customClasses object to the propertiesPanel options. We would like to know if this is an improvement you are considering for a future release or have any suggestions.

**Comment by nikku** [comment]
It would be nice to get a bit more background why you guys need such functionality.

Based on your implementation and the use-cases it enables we can consider merging it in. Please provide a PR with the changes so that we can have a look inside the stuff you implemented.

**Comment by billbarni** [comment]
Is this why I can't customize my component's CSS?

![image](https://user-images.githubusercontent.com/21037830/176929746-2995369f-6db7-470b-84ac-5861450ab2ac.png)

I can't unset the parent CSS no matter what I do so my component behaves correctly.
What is the correct aproach? I always end up inheriting 'bio-properties-panel', and my 'unset' does not work.

**Comment by barmac** [comment]
No, this unrelated. For you issue, please read more on the specificity in CSS to find out why it works this way: https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity.

Now when I read the OP comment again, I feel we'd need to clarify this issue as it's not 100% clear what this is about. Still, as we haven't heard from OP after the issue was created, I think it can be closed. We can always reopen the issue when there's interest.
