### ISSUE TITLE
Editing camunda:formKey and camunda:formData at the same time on user task

### ISSUE THREAD

**Issue by rjaros** [bpmn-io/bpmn-js-properties-panel#206]
In eclipse based camunda modeler it is possible to set camunda:formKey and to define form fields in camunda:formData element at the same time. In bpmn-io based modeler it is not possible.

**Comment by nikku** [comment]
From the perspective of the Camunda engine this does not make any sense. Or am I missing anything?

**Comment by rjaros** [comment]
We are developing our own Camunda-based application, which renders forms for user tasks. We are using camunda:formKey to declare "default" form - it's in fact an URL address  to a specific page in our client application. But at the same time we allow to declare some additional camunda:formFields, which are rendered at the bottom of the default form. Of course we could use different user task properties for that purpose (e.g. an extension), but formKey and formData seems well-suited and Eclipse based modeler allows it. Now we are trying to migrate to new modeler and it is not possible. We would rather not change whole application logic and a bunch of already designed processes so could You please reconsider?

**Comment by michal-drozd** [comment]
I have similiar problem. Although some of components of our app are developed externally. So changing whole semantics of bpmn processes (in this case the way of handling mixing formData and external form handler's formKey) is almost impossible (and for my managers undoubtedly "too costly"). 
In my case there are bunch of cases where the whole app is relying on possibility of mixing external forms with built in form definitions through formData. The main case is fast prototyping of form using formData. External form is created later and it is simply added using formKey, but formData section are still used to verify and ensure, that all subsequent tasks will receive necessary process variables. This is crucial for our team because our app is relying on camunda engine for orchestrating services in SOA way. 

Since camunda modeler is the only "officially supported" way of editing bpmns with camunda extensions visually, there shouldn't be such  restrictions which are irrelevant for camunda engine. 

Please consider this change once again.

**Comment by meyerdan** [comment]
We should decide whether the request makes sense after all
