### ISSUE TITLE
Fill elements inital drag

### ISSUE THREAD

**Issue by oedemis** [bpmn-io/bpmn-js-properties-panel#317]
How I can fill elements initally, if I select a component.
For example if the user drags an Task it should fill Input/Output Properties with some values.
Iam implementing based on property-panel example

**Comment by pinussilvestrus** [comment]
All element's properties are stored inside its `businessObject`, so you can simply edit them. They will then displayed in the properties panel. You can also use [`modeling#updateProperties`](https://github.com/bpmn-io/bpmn-js/blob/develop/lib/features/modeling/Modeling.js#L87) for doing that in a cleaner way.

I'll close this since no real issue is described. Please refer to [our forum](https://forum.bpmn.io/) for asking future questions. The GitHub issues are intended for bug reports and feature requests.
