### ISSUE TITLE
Better distinguish template tasks from plain service tasks

### ISSUE THREAD

**Issue by nikku** [bpmn-io/bpmn-js-properties-panel#610]
__Is your feature request related to a problem? Please describe__

In the properties panel template tasks are not really distinguishable from their standard BPMN counterparts: 

![image](https://user-images.githubusercontent.com/58601/158219947-6691c6ca-4ccc-44ad-b172-83de21c4e5a1.png)

What I need to do is look for the template section, and more specifically expand it to get hold on the template name.

__Describe the solution you'd like__

* The name of the template shall be more prominently displayed by the properties panel; in the screenshot above, it shall read `SendGrid Email Template Task` if the element template author chose that name:
* Going beyond that the properties panel shall display the element templates icon (cf. https://github.com/bpmn-io/internal-docs/issues/445, if specified).

Both help us to clearly distinguish templated tasks from the elements they are built upon:

_Cf. design sketch:_

![image](https://user-images.githubusercontent.com/58601/158794676-cf748ff5-32e4-44f2-a896-021a66cef82d.png)

__Describe alternatives you've considered__

Do nothing.

**Comment by pinussilvestrus** [comment]
According to https://github.com/bpmn-io/internal-docs/issues/445#issuecomment-1067860304, we want to have it, but not as an immediate next work item. Therefore I'm moving it to the backlog.

**Comment by pinussilvestrus** [comment]
This will need the existing [panel header provider](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/render/PanelHeaderProvider.js#L65) to be not only dynamic to the chosen element, but also to another context (e.g. element template applied).

I could imagine firing an event on getting the label / type / icon so that other modules (e.g. element templates, my extension) can hook into. E.g.

* `propertiesPanel.header.getLabel`
* `propertiesPanel.header.getType`
* `propertiesPanel.header.getIcon`

**Comment by pinussilvestrus** [comment]
This would also help us in terms of the planned template icons (https://github.com/bpmn-io/internal-docs/issues/445).

**Comment by pinussilvestrus** [comment]
Alternative: accept that element templates are a core concern of the properties panel and implement these things into the existing panel header provider (in case an `element-template` service is injectable). 

That would also be fine, given the [`BpmnPropertiesPanel` already knows about element templates](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/src/render/BpmnPropertiesPanel.js#L141) (kind of).

**Comment by nikku** [comment]
I'd go for option two: Understand that element templates is a thing and account for that. Consider however that `elementTemplates` may also not be used (i.e. handle it as an optional dependency).

Let us not make things super-dynamic at this stage.

**Comment by pinussilvestrus** [comment]
To clarify what I read out of the requirements: given an element template applied, the properties panel will show the "name" of the element template instead of the type.

without element template
![image](https://user-images.githubusercontent.com/9433996/159929593-da12e091-cde6-4b66-bab3-4c3fdbab1655.png)

with element template
![image](https://user-images.githubusercontent.com/9433996/159929428-615898ed-4a95-449a-8927-45faa937af2a.png)

Is this correct? @nikku @currandwyer

**Comment by pinussilvestrus** [comment]
Edit: just saw the design sketch, which answers my question, sorry 🙂
